### ISSUE TITLE
dashboard map doesn't show up when run on phone (Android)

### ISSUE THREAD

**Issue by lusilva** [michael-han/DriveSafe#14]
The google maps doesn't appear when I run it as a cordova app on my phone.

**Comment by michael-han** [comment]
Is there a way to read terminal output when it's running on the phone?

**Comment by lusilva** [comment]
Yes, and no errors are output to terminal

**Comment by michael-han** [comment]
Alright, great. Then it might be an issue if Google can somehow detect if it's a mobile request vs desktop request? Or is there an issue publishing on a small screen size?

**Comment by lusilva** [comment]
I don't think its a problem with Google, seemed to be working prior to adding Ionic. Might be a problem with how we set the map in the background.
